language: generic

install:
  - mkdir -p travis-secrets/private_key
  - echo ${TRAVIS_PRIVATE_KEY} | tr '_' '\n' > travis-secrets/private_key/private_key.pem
  - (cd travis-secrets/ && ./decrypt.sh)
  - cat travis-secrets/decrypted/sample_secret.txt
  - make emsdk
  - source build/root/native/emsdk/emsdk_env.sh
  - make deps

script:
  - make -C modules/mestring/
