language: generic

install:
  - echo ${TRAVIS_PRIVATE_KEY} | tr '_' '\n' > travis-secrets/private_key/private_key.pem
  - ./tools/run_travis.sh

script:
  - clang++ --version && make -C modules/mestring/ && ./modules/mestring/test_mestring && echo "PASSED!"
