language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-6-dev
      - libstdc++6

install:
  - mkdir -p travis-secrets/private_key/
  - echo ${TRAVIS_PRIVATE_KEY} | tr '_' '\n' > travis-secrets/private_key/private_key.pem
  - ./tools/run_travis.sh

script:
  - ./tools/run_on_travis.sh
