language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

install:
  - mkdir -p travis-secrets/private_key/
  - echo ${TRAVIS_PRIVATE_KEY} | tr '_' '\n' > travis-secrets/private_key/private_key.pem
  - source ./tools/run_travis.sh
  - source build/root/native/emsdk/emsdk_env.sh

script:
  - clang++ --version && make -C modules/mestring/ && ./modules/mestring/test_mestring && echo "PASSED!"
