language: generic

install:
  - mkdir -p travis-secrets/private_key
  - echo ${TRAVIS_PRIVATE_KEY} | tr '_' '\n' > travis-secrets/private_key/private_key.pem
  - (cd travis-secrets/ && ./decrypt.sh)
  - cat travis-secrets/decrypted/sample_secret.txt
  - make cmake
  - export $PATH=$PWD/build/root/native/cmake/bin:$PATH
  - cmake --version
  - make emsdk
  - source build/root/native/emsdk/emsdk_env.sh
  - clang++ --version
  - make deps

script:
  - clang++ --version && make -C modules/mestring/ && ./modules/mestring/test_mestring && echo "PASSED!"
