language: generic

addons:
  apt:
    packages:
      - openssl

install:
  - mkdir -p travis-secrets/private_key
  - echo ${TRAVIS_PRIVATE_KEY} | tr '_' '\n' > travis-secrets/private_key/private_key.pem
  - $(cd travis-secrets/ && ./decrypt.sh)
  - cat travis-secrets/decrypted/sample_secret.txt

script: echo "no tests"
